# Generated by Django 3.0.3 on 2020-03-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='summary',
            field=models.CharField(max_length=300),
        ),
    ]
