# Generated by Django 3.0.3 on 2020-02-16 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=20)),
                ('blogdate', models.DateTimeField()),
                ('blogtext', models.TextField()),
                ('blogmedia', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
